[package]
name = "rhai_rustler"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "rhai_rustler"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.34.0"
rhai = "1.16.0"
lazy_static = "1.4.0"
